#!/usr/bin/env python3

#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


#Terms go odd, odd, even
#Term 8 = term 7 + term 6
#       = term 6 + 2 * term 5 + term 4
#       = 3 * term 5 + term 4 + term 3 + term 2
#       = 4 * term 5 + term 2

val_1 = 2
val_2 = 8
ans = val_1

while val_2 < 4000000:
    ans += val_2
    (val_1, val_2) = (val_2, 4*val_2 + val_1)

print(ans)
